### ISSUE TITLE
Isnt it more likely to get a match than a popup?

### ISSUE THREAD

**Issue by T0biii** [aj-4/tinder-swipe-bot#11]
Isnt it more likely to get a match?
https://github.com/aj-4/tinder-swipe-bot/blob/936ac54b9202d4daa7787590239ae24769daf844/tinder_bot.py#L56
than a popup?
https://github.com/aj-4/tinder-swipe-bot/blob/936ac54b9202d4daa7787590239ae24769daf844/tinder_bot.py#L54

so we should swap close_popup with close_match?

**Comment by Sunney-X** [comment]
depends on the person...

**Comment by T0biii** [comment]
so he says we are all ugly? im i right xD
