### ISSUE TITLE
Can't get the like button to work.

### ISSUE THREAD

**Issue by jmedinajr444** [aj-4/tinder-swipe-bot#20]
Keep in mind that I'm pretty new to programming:

I think it might have something to do with the xpath.

like_btn = self.driver.find_element_by_xpath('//[@id="content"]/div/div[1]/div/div/main/div/div[1]/div/div[2]/div[4]/button')
        

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="content"]/div/div[1]/div/div/main/div/div[1]/div/div[2]/div[4]/button"}
  (Session info: chrome=80.0.3987.149)

**Comment by dineshrathee12** [comment]
Yeah, I'm new , learning things, will check that , Thanks for feedback @jmedinajr444  :)

**Comment by jmedinajr444** [comment]
Guess all you have to do is 'copy the full xpath'. *self five*
